region = "us-central1"
gcp_project = "cloudglobaldelivery-1000135575"
credentials= "credentials.json"
kafkavpc = "default"
kafkasub = "default"
instance_name = "kafka"
kafka_instance_ip_name = "kafkaip"
kafka_instance_ip_region = "us-east1"
