variable "region" {}
variable "gcp_project" {}
variable "credentials" {}
variable "kafka1vpc" {}
variable "kafka1sub" {}
variable "kafka2vpc" {}
variable "kafka2sub" {}
variable "kafka3vpc" {}
variable "kafka3sub" {}
variable "instance_name1" {}
variable "instance_name2" {}
variable "instance_name3" {}
variable "kafka1_instance_ip_name" {}
variable "kafka2_instance_ip_name" {}
variable "kafka3_instance_ip_name" {}
variable "kafka_instance_ip_region" {}
